[package]
name = "gutenberg"
version = "0.4.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "A fast static site generator with everything built-in"
homepage = "https://github.com/Keats/gutenberg"
repository = "https://github.com/Keats/gutenberg"
keywords = ["static", "site", "generator", "blog"]
# build = "build.rs"

[build-dependencies]
clap = "2"

[[bin]]
name = "gutenberg"

[dependencies]
clap = "2"
chrono = "0.4"
toml = "0.4"
term-painter = "0.2"
# Used in init to ensure the url given as base_url is a valid one
url = "1.5"
# Below is for the serve cmd
actix = "0.6"
actix-web = "0.6"
notify = "4"
ws = "0.7"
ctrlc = "3"

site = { path = "components/site" }
errors = { path = "components/errors" }
content = { path = "components/content" }
front_matter = { path = "components/front_matter" }
utils = { path = "components/utils" }
rebuild = { path = "components/rebuild" }

[workspace]
members = [
    "components/config",
    "components/content",
    "components/errors",
    "components/front_matter",
    "components/highlighting",
    "components/pagination",
    "components/rebuild",
    "components/rendering",
    "components/site",
    "components/taxonomies",
    "components/templates",
    "components/utils",
    "components/search",
]
